### PR TITLE
fix: {N} 7 support

### PR DESCRIPTION
**Pull request by NathanWalker**
* just clean and rebuild plugin and all set.

### CODE REVIEW

**Comment by trevortos** [comment]
I think there might be a few more things that need to be changed.
https://nativescript.org/blog/nativescript-7-for-plugin-authors/

**Comment by NathanWalker** [comment]
Eddy already cleared the other things needed here:
https://github.com/EddyVerbruggen/nativescript-barcodescanner/commit/8a792af288837c1a6031aa1ad44664f470e36b4b

This just finishes off the last piece with the NativeClass handling and the tsconfig update which is why 4.0.0 is not working. Can just bump a path and publish @EddyVerbruggen 🆗

**Comment by EddyVerbruggen** [comment]
Cool, that seems to get rid of that `NativeClass` indeed. Thanks, Nathan!

I just released this as 4.0.1 to npm.

While testing I found that setting `beepOnScan` to `true` may crash iOS. There seems to be a recent (iOS 14 or NativeScript 7) change (need to dig in that to blame one or the other) which crashes the audioplayer which is responsible for beeping on scan. Seems to happen after the second or third scan with the demo app. So for now, I added a note to the top of the readme.

**Comment by NathanWalker** [comment]
Excellent @EddyVerbruggen thanks - yes the beepOnScan is likely a subtle change in iOS 14 and/or may only properly work on device? Either no big deal (developers can also implement their own beep sound effects on result returned) thank you!

**Pull request merged**
